name: Terraform apply
on:
  workflow_dispatch:
  
env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.0
  TERRAGRUNT_VERSION: 0.31.1
  CONFTEST_VERSION: 0.27.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::017790921725:role/AWSLambdaTrafficShiftingDemoAdministratorRole
          role-session-name: AWSLambdaTrafficShiftingDemoGitHubActions
          aws-region: "ca-central-1"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Publish new lambda version
        run: |
          aws lambda wait function-updated --function-name aws_lambda_traffic_shifting_action_demo
          echo "VERSION=$(aws lambda publish-version --function-name aws_lambda_traffic_shifting_action_demo | jq -r '.Version')" >> $GITHUB_ENV

      - name: Shift lambda traffic over 10 minutes
        uses: cds-snc/aws-lambda-traffic-shifting-action@6b134de1b3404f6c12331f5cf25904671228a960 # 0.4
        env:
          ALIAS: aws_lambda_traffic_shifting_action_demo
          FUNCTION_NAME: aws_lambda_traffic_shifting_action_demo
          BLUE_VERSION: "2"
          GREEN_VERSION: "${{ env.VERSION }}"
          ROLLOUT_STEPS: 5
          ROLLOUT_TIME_IN_MINUTES: 10
