name: Terraform plan
on:
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.0
  TERRAGRUNT_VERSION: 0.31.1
  CONFTEST_VERSION: 0.27.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: terraform

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::017790921725:role/AWSLambdaTrafficShiftingDemoReadOnlyRole
          role-session-name: AWSLambdaTrafficShiftingDemoGitHubActions
          aws-region: "ca-central-1"

      - name: Terraform Plan ${{ matrix.module }}
        uses: cds-snc/terraform-plan@8be66db9c815352044405fd33120b91918bf1f2e # v2.3.1
        with:
          comment-delete: true
          comment-title: Plan for ${{ matrix.module }}
          directory: ./${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
